### ISSUE TITLE
what exactly does this mod fix?

### ISSUE THREAD

**Issue by viiuan** [ZehsTeam/Lethal-Company-LCBetterSavesFix#1]
can't ask anywhere else so i'll do it here. i've used LCBetterSaves for a while with LethalModDataLib installed and enabled and i've had nothing go wrong. what does this fix do then, specifically?

**Comment by ZehsTeam** [comment]
@viiuan I've had many issues with LCBetterSaves + LethalModDataLib where my modded data would not save/load.

When you start a new save file, LCBetterSaves overrides the game's currentSaveFileName to the wrong name which makes LethalModDataLib  save your modded data to the wrong file.

When you delete save files with LCBetterSaves, all your LethalModDataLib save data might be lost because of how LCBetterSaves manages save files and how LethalModDataLib saves data.

This mod fixes all of that.
